name: Notify Dependents
on:
  push:
    paths:
      - 'tokens/**'
      - 'components/**'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Dependents
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}
          event-type: brand-update
          client-payload: '{"version": "${{ github.sha }}", "actor": "${{ github.actor }}"}'
          repositories: |
            INSPIRON-TECH-BD/CORE_MISSION-CONTROL-WEB
            CyberHasan/command-node-demo
            INSPIRON-TECH-BD/CLIENT_MSINTL-SMART-DASHBOARD
